const GET_WORKSHOPS = 'GET_WORKSHOPS';
const AUTH_USER = 'AUTH_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const GET_DETAILS = 'GET_DETAILS';
const CREATE_ATTENDANCE = 'CREATE_ATTENDANCE';

export {
  GET_WORKSHOPS,
  AUTH_USER,
  LOGOUT_USER,
  GET_DETAILS,
  CREATE_ATTENDANCE,
};
