const GET_WORKSHOPS = 'GET_WORKSHOPS';
const AUTH_USER = 'AUTH_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const GET_DETAILS = 'GET_DETAILS';
const GET_ATTENDANCES = 'GET_ATTENDANCES';
const SET_ERROR = 'SET_ERROR';
const RESET_ERROR = 'RESET_ERROR';

export {
  GET_WORKSHOPS,
  AUTH_USER,
  LOGOUT_USER,
  GET_DETAILS,
  GET_ATTENDANCES,
  SET_ERROR,
  RESET_ERROR,
};
