const GET_WORKSHOPS = 'GET_WORKSHOPS';
const AUTH_USER = 'AUTH_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const ATTEND_WORKSHOP = 'ATTEND_WORKSHOP';

export {
  GET_WORKSHOPS,
  AUTH_USER,
  LOGOUT_USER,
  ATTEND_WORKSHOP,
};
